version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
